version: 0.2

phases:   
  install: 
   runtime-versions: 
    docker: 20
   commands: 
      #- echo "Checking if curl is installed..."
      #- if command -v curl > /dev/null; then echo "curl is installed"; else echo "curl is not installed"; fi
      #- echo "Installing Docker Buildx"
      #- mkdir -p ~/.docker/cli-plugins
      #- curl -SL https://github.com/docker/buildx/releases/latest/download/buildx-$(uname -s)-$(uname -m) -o ~/.docker/cli-plugins/docker-buildx
      #- chmod +x ~/.docker/cli-plugins/docker-buildx
     
  pre_build: 
    commands: 
      - echo Logging into ECR 
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build: 
    commands:
      - echo Starting build at `date`
      - echo building the docker image...
      #- docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER .
      - docker build -t $IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER .
      - docker tag $IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER


  post_build: 
    commands:
      - echo Completed build at `date`
      - echo Pushing the docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER
