apiVersion: v1
kind: Service
metadata:
  name: coworking
spec:
  type: LoadBalancer
  selector:
    service: coworking
  ports:
  - name: "5153"
    protocol: TCP
    port: 5153
    targetPort: 5153
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking
  labels:
    name: coworking
spec:
  replicas: 1
  selector:
    matchLabels:
      service: coworking
  template:
    metadata:
      labels:
        service: coworking
    spec:
      containers:
      - name: coworking
        image: 535002849786.dkr.ecr.us-east-1.amazonaws.com/udacity-project3:0.0.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        env:  # Ensure this is indented correctly
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_PASSWORD  # Ensure this key exists in the Secret
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_USERNAME  # Ensure this key exists in the Secret             
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: postgresql-service-configmap  # Ensure this ConfigMap exists
              key: DB_NAME  # Ensure this key exists in the ConfigMap
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: postgresql-service-configmap  # Ensure this ConfigMap exists
              key: DB_HOST  # Ensure this key exists in the ConfigMap
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: postgresql-service-configmap  # Ensure this ConfigMap exists
              key: DB_PORT  # Ensure this key exists in the ConfigMap
    
